from setuptools import setup

setup(
    name='FindItNow',
    version='',
    packages=['python.Lib.site-packages.idna', 'python.Lib.site-packages.certifi', 'python.Lib.site-packages.chardet',
              'python.Lib.site-packages.chardet.cli', 'python.Lib.site-packages.telebot',
              'python.Lib.site-packages.urllib3', 'python.Lib.site-packages.urllib3.util',
              'python.Lib.site-packages.urllib3.contrib', 'python.Lib.site-packages.urllib3.contrib._securetransport',
              'python.Lib.site-packages.urllib3.packages', 'python.Lib.site-packages.urllib3.packages.backports',
              'python.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'python.Lib.site-packages.requests',
              'python.Lib.site-packages.requests.packages', 'python.Lib.site-packages.requests.packages.chardet',
              'python.Lib.site-packages.requests.packages.urllib3',
              'python.Lib.site-packages.requests.packages.urllib3.util',
              'python.Lib.site-packages.requests.packages.urllib3.contrib',
              'python.Lib.site-packages.requests.packages.urllib3.packages',
              'python.Lib.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'python.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='Alexey Bobko',
    author_email='',
    description=''
)
